### ISSUE TITLE
SheepMonitor doesn't seem to recognise the new mage spell: Polymorph: Mosswool

### ISSUE THREAD

**Issue by gyre** [funkjedi/SheepMonitor#12]
I've just learned the spell Polymorph: Mosswool, which appeared in 11.0.  

Could SheepMonitor be changed to recognise this particular polymorph?

Thanks!

**Comment by funkjedi** [comment]
nice, hadn't seen that yet. out of town for thanksgiving but i'll take a look at it when i get back later this week.

**Comment by gyre** [comment]
Brill, thanks.   :)

**Comment by gyre** [comment]
I did try coding it myself.  I found the spell id and what I thought was the icon path for the aura from wowhead, but I got an error later in the code which I've not had time to debug yet.  :)

 [460392] = 'Interface\\Icons\\Inv_Collections_Armor_Flowerbracelet_A_01', -- Polymorph (Mosswool)

**Comment by speedwaystar** [comment]
main.lua, add line 23:
LibAuraInfo.auraInfo[460392]  = '60;1' -- updating polymorph value for TWW

**Comment by funkjedi** [comment]
Added to latest release

**Comment by gyre** [comment]
Thanks!  :)
